
project_id = "swrfsullhirscyxqneay"

[functions.glsync]
verify_jwt = false

[functions.process-account-balance-queue]
verify_jwt = false

[functions.store-pdf]
verify_jwt = false

[functions.batch-generate-and-store-pdfs]
verify_jwt = false
